// frontend/src/components/LoginForm.tsx
import { useState } from 'react'
import { useAuth } from '../contexts/AuthContext'

interface LoginFormProps {
  onSwitchToRegister?: () => void
}

export function LoginForm({ onSwitchToRegister }: LoginFormProps) {
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    rememberMe: false
  })
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isLoading, setIsLoading] = useState(false)
  const { login } = useAuth()

  const validateForm = () => {
    const newErrors: Record<string, string> = {}

    if (!formData.email) {
      newErrors.email = 'Email is required'
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Invalid email format'
    }

    if (!formData.password) {
      newErrors.password = 'Password is required'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return

    setIsLoading(true)
    try {
      await login(formData.email, formData.password, formData.rememberMe)
    } catch (error) {
      setErrors({ general: error instanceof Error ? error.message : 'Login failed' })
    } finally {
      setIsLoading(false)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value, type, checked } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }))
    
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => ({ ...prev, [name]: '' }))
    }
  }

  return (
    <div className="w-full max-w-md mx-auto">
      <div className="bg-white shadow-md rounded-lg px-8 pt-6 pb-8 mb-4">
        <h2 className="text-2xl font-bold text-center text-gray-900 mb-6">Sign In</h2>
        
        <form onSubmit={handleSubmit} className="space-y-4">
          {errors.general && (
            <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
              {errors.general}
            </div>
          )}

          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-1">
              Email
            </label>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleChange}
              className={`form-input ${errors.email ? 'error' : ''}`}
              placeholder="Enter your email"
              disabled={isLoading}
            />
            {errors.email && (
              <p className="mt-1 text-sm text-red-600">{errors.email}</p>
            )}
          </div>

          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-1">
              Password
            </label>
            <input
              type="password"
              id="password"
              name="password"
              value={formData.password}
              onChange={handleChange}
              className={`form-input ${errors.password ? 'error' : ''}`}
              placeholder="Enter your password"
              disabled={isLoading}
            />
            {errors.password && (
              <p className="mt-1 text-sm text-red-600">{errors.password}</p>
            )}
          </div>

          <div className="flex items-center">
            <input
              type="checkbox"
              id="rememberMe"
              name="rememberMe"
              checked={formData.rememberMe}
              onChange={handleChange}
              className="h-4 w-4 text-brand-600 focus:ring-brand-500 border-gray-300 rounded"
              disabled={isLoading}
            />
            <label htmlFor="rememberMe" className="ml-2 block text-sm text-gray-900">
              Remember me
            </label>
          </div>

          <button
            type="submit"
            disabled={isLoading}
            className="w-full btn btn-primary"
          >
            {isLoading ? 'Signing in...' : 'Sign In'}
          </button>
        </form>

        {onSwitchToRegister && (
          <p className="mt-4 text-center text-sm text-gray-600">
            Don't have an account?{' '}
            <button
              type="button"
              onClick={onSwitchToRegister}
              className="font-medium text-brand-600 hover:text-brand-500"
              disabled={isLoading}
            >
              Sign up
            </button>
          </p>
        )}
      </div>
    </div>
  )
}

// frontend/src/lib/components/auth/LoginForm.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';

	// Props
	export let loading = false;
	export let error: string | null = null;

	// Form data
	let email = '';
	let password = '';
	let rememberMe = false;

	// Form validation
	let emailError = '';
	let passwordError = '';
	let formValid = false;

	// Event dispatcher
	const dispatch = createEventDispatcher<{
		login: { email: string; password: string; rememberMe: boolean };
	}>();

	// Validate form input
	function validateEmail() {
		if (!email) {
			emailError = 'Email is required';
			return false;
		}
		const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
		if (!emailRegex.test(email)) {
			emailError = 'Please enter a valid email address';
			return false;
		}
		emailError = '';
		return true;
	}

	function validatePassword() {
		if (!password) {
			passwordError = 'Password is required';
			return false;
		}
		passwordError = '';
		return true;
	}

	function validateForm() {
		const isEmailValid = validateEmail();
		const isPasswordValid = validatePassword();
		formValid = isEmailValid && isPasswordValid;
		return formValid;
	}

	// Handle form submission
	function handleSubmit() {
		if (validateForm()) {
			dispatch('login', { email, password, rememberMe });
		}
	}
</script>

<div class="mx-auto w-full max-w-md p-4">
	<div class="text-center mb-8">
		<h1 class="text-3xl font-bold mb-2">Welcome back</h1>
		<p class="text-base-content/70">Sign in to continue to your account</p>
	</div>

	{#if error}
		<div class="bg-red-50 border-l-4 border-red-500 p-4 mb-6 rounded-lg">
			<div class="flex items-start">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-red-500 mt-0.5 mr-3">
					<circle cx="12" cy="12" r="10"/>
					<line x1="12" x2="12" y1="8" y2="12"/>
					<line x1="12" x2="12.01" y1="16" y2="16"/>
				</svg>
				<span class="text-red-700">{error}</span>
			</div>
		</div>
	{/if}

	<form on:submit|preventDefault={handleSubmit} class="space-y-6">
		<div>
			<label for="email" class="block text-sm font-medium mb-2">
				Email address
			</label>
			<input
				type="email"
				id="email"
				bind:value={email}
				on:blur={validateEmail}
				placeholder="you@example.com"
				class="w-full px-4 py-3 rounded-lg border border-base-300 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
				disabled={loading}
				autocomplete="email"
			/>
			{#if emailError}
				<p class="mt-1.5 text-sm text-red-600">{emailError}</p>
			{/if}
		</div>

		<div>
			<div class="flex justify-between items-center mb-2">
				<label for="password" class="block text-sm font-medium">
					Password
				</label>
				<a href="#" class="text-sm text-brand-600 hover:text-brand-500">Forgot password?</a>
			</div>
			<input
				type="password"
				id="password"
				bind:value={password}
				on:blur={validatePassword}
				placeholder="••••••••"
				class="w-full px-4 py-3 rounded-lg border border-base-300 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:border-brand-500"
				disabled={loading}
				autocomplete="current-password"
			/>
			{#if passwordError}
				<p class="mt-1.5 text-sm text-red-600">{passwordError}</p>
			{/if}
		</div>

		<div class="flex items-center">
			<input
				id="remember"
				type="checkbox"
				bind:checked={rememberMe}
				class="h-4 w-4 rounded border-base-300 text-brand-600 focus:ring-brand-500"
				disabled={loading}
			/>
			<label for="remember" class="ml-2 block text-sm">
				Remember me for 30 days
			</label>
		</div>

		<div>
			<button 
				type="submit" 
				class="hover-lift w-full py-3 bg-gradient-to-br from-brand-500 to-brand-600 text-white font-medium rounded-lg shadow flex items-center justify-center" 
				disabled={loading}
			>
				{#if loading}
					<svg class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
						<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
						<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
					</svg>
				{/if}
				Sign in
			</button>
		</div>

		<div class="mt-6 text-center">
			<p class="text-base-content/70">
				Don't have an account?
				<a href="/register" class="font-medium text-brand-600 hover:text-brand-500">
					Create one now
				</a>
			</p>
		</div>
	</form>
</div>
